# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{primadoro}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy McAnally"]
  s.date = %q{2010-07-30}
  s.default_executable = %q{primadoro}
  s.description = %q{A gem for executing custom actions during Pomodoros}
  s.email = %q{jeremymcanally@gmail.com}
  s.executables = ["primadoro"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/primadoro.rb",
     "resources/bell.mp3",
     "resources/windup.wav",
     "test/helper.rb",
     "test/test_primadoro.rb"
  ]
  s.homepage = %q{http://github.com/jm/primadoro}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A neato gem for helping with Pomodoros}
  s.test_files = [
    "test/helper.rb",
     "test/test_primadoro.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

